name: CI/CD Pipeline

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'etc/settings.json'
      - 'LICENSE'
      - '*.md'
      - 'start.sh'
      - 'stop.sh'

jobs:
  workflow:
    name: Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Download the project files
        uses: actions/checkout@v3

      - name: Build and Publish
        env:
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
          DOCKER_REGISTRY_ID: ${{ secrets.DOCKER_REGISTRY_ID }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: ./build.sh
